### ISSUE TITLE
SortOrder issue

### ISSUE THREAD

**Issue by tillzzz** [bummzack/page-blocks#5]
Hi there!
When deleting a block and adding a new one, the new SortOrder - value is not correct.
(Same SortOrder - value on two blocks )
Sorting fails from that moment.
thanks.
timo.

**Comment by bummzack** [comment]
I think your issue was introduced due to the `Sortable` extension.

I've removed the `Sortable` dependency for Blocks. I think sorting is such a prevalent use-case that it doesn't make sense to make it configurable. So sorting is now always available and the sorting-column is base of the `Block` class.

Please update to the latest version of this module and remove the `Sortable` extension from Block! 
Let me know if that helps.
